version: '3.8'

services:
  backend:
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.password=
      - spring.datasource.username=
      - token=